{% set name = "ansys-mechanical-env" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ansys_mechanical_env-{{ version }}.tar.gz
  sha256: 29a4ce796cf3719828f6af4fa7d1097333cb12d1b10b6ab199efe0f7ec8fc346

build:
  noarch: python
  entry_points:
    - find-mechanical=ansys.mechanical.env.run:cli_find_mechanical
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4
    - setuptools
    - wheel
    - pip
  run:
    - python >=3.9,<4
    - importlib-metadata >=4.0
    - ansys-tools-path >=0.3.1
    - click >=8.1.3

test:
  imports:
    - ansys.mechanical.env
  commands:
    - pip check
    - find-mechanical --help
  requires:
    - pip

about:
  home: https://github.com/ansys/pymechanical-env
  summary: A python wrapper for loading environment variables when using PyMechanical embedded instances in Linux.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dipinknair
    - koubaa
    - RobPasMue
