{% set name = "ansys-mechanical-env" %}
{% set version = "0.1.14" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ansys_mechanical_env-{{ version }}.tar.gz
  sha256: 6383c78a2f9efaa0c978c9c6a9fdfbb6e07820f5a9155ad870e7291a5da570b4

build:
  noarch: python
  entry_points:
    - find-mechanical=ansys.mechanical.env.run:cli_find_mechanical
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }},<4
    - importlib-metadata >=4.0
    - ansys-tools-path >=0.3.1
    - click >=8.1.3

test:
  imports:
    - ansys.mechanical.env
  commands:
    - pip check
    - find-mechanical --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ansys/pymechanical-env
  summary: A python wrapper for loading environment variables when using PyMechanical embedded instances in Linux.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dipinknair
    - koubaa
    - RobPasMue
